version: '3.3'
services:
  app:
    build: .
    networks:
      - my-network
    volumes:
      - .:/app
  pg:
    image: postgres
    networks:
      - my-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test


networks:
  my-network:
    driver: bridge