package ru.homework.tasktracker.model;

public enum StrategyName {
    TASK_CREATE,
    TASK_DELETE,
    TASK_EDIT,
    TASK_VIEW,
    TASK_VIEW_ALL,
    USER_CREATE,
    USER_DELETE,
    USER_EDIT,
    USER_VIEW,
    USER_VIEW_ALL,
    USER_WITH_MAX_NUMBER_TASKS,
    USER_ADD_PROJECT,
    COMMENT_CREATE,
    COMMENT_DELETE,
    COMMENT_EDIT,
    COMMENT_VIEW,
    COMMENT_VIEW_ALL,
    PROJECT_CREATE,
    PROJECT_DELETE,
    PROJECT_EDIT,
    PROJECT_VIEW,
    PROJECT_VIEW_ALL
}
